package io.somi.rag.di

import android.content.Context
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import io.objectbox.BoxStore
import io.somi.rag.MyObjectBox
import javax.inject.Singleton

/**
 * v0.14.0 M1 — Hilt module providing the lazy [BoxStore] singleton.
 *
 * The store lives at `$filesDir/objectbox/so-mi-rag/` (NOT
 * external storage — the binary DB is authoritative; the
 * user-readable `.md` mirror in M4 lives at
 * `$externalFilesDir/memory/`).
 *
 * `MyObjectBox` is generated by the `io.objectbox` Gradle plugin
 * at compile time once at least one `@Entity` exists in this
 * module — see `internal/_Bootstrap.kt` for the M1 placeholder.
 */
@Module
@InstallIn(SingletonComponent::class)
internal object RagModule {

    /**
     * BoxStore is a heavy singleton; opening it costs JNI init +
     * filesystem touch + schema check. Hilt scopes it `@Singleton`
     * so the cost is amortized over the process lifetime, and
     * `RagBootstrap` injects it via `dagger.Lazy` so the open
     * happens on first use, not at injection-graph construction.
     */
    @Provides
    @Singleton
    fun provideBoxStore(@ApplicationContext context: Context): BoxStore =
        MyObjectBox.builder()
            .androidContext(context.applicationContext)
            .name(DB_NAME)
            .build()

    /** Stable name; bumping it would orphan all existing facts. */
    private const val DB_NAME = "so-mi-rag"
}
