package io.somi.common.chat

/**
 * A single line in the chat transcript.
 *
 * Lives in `core-common` next to [ChatState] so every layer (`core-ui`,
 * `app`, future `core-rag`) can speak in the same vocabulary without
 * forming a cross-`core-*` dependency cycle.
 *
 * Messages are append-only inside the [io.somi.ui.chat.ChatViewModel] —
 * the live-typing partial response is NOT a Message; it lives in the
 * [ChatState.Generating.partialResponse] field. Only when generation
 * completes (or is cancelled with non-empty partial text) does the
 * ViewModel commit a final `ASSISTANT` Message to the history.
 *
 * @param id monotonic, generated by the ViewModel via an
 *   [java.util.concurrent.atomic.AtomicLong]. Keys the LazyColumn item
 *   in the chat surface — so it MUST be stable across recompositions
 *   and unique within a session. Not persisted across process death in
 *   Phase 2.6; persistence comes with Phase 3.
 * @param author who said it; see [Author]
 * @param text the literal payload. For USER this is the raw composer
 *   input; for ASSISTANT this is the final accumulated stream output
 *   (with no chat-template markers — those are handled inside
 *   `LlamaCppContext`).
 * @param timestamp `System.currentTimeMillis()` at append time. Wall
 *   clock, not monotonic — fine for ordering within a session but don't
 *   diff two of these to time a generation.
 */
data class Message(
    val id: Long,
    val author: Author,
    val text: String,
    val timestamp: Long,
)

/** Who authored a [Message]. */
enum class Author { USER, ASSISTANT }
